### ISSUE TITLE
Wrong link of CEP draft github link

### ISSUE THREAD

**Issue by hanyuwei70** [fido-alliance/credential-exchange-feedback#18]
## Description

In https://fidoalliance.org/specs/cx/cxp-v1.0-wd-20240522.html
The Issue Tracking url is 404.

### Steps to reproduce

Click "Issue Tracking" github link.

### Expected result

Should open

### Actual result

404

**Comment by irew** [comment]
This is normal as with all FIDO specifications as it points to a private repository for internal issue tracking. This current repository is explicitly public in order to gather feedback from non-FIDO members.

**Comment by dturnerx** [comment]
I will update the specs to point to this repo.

**Comment by dturnerx** [comment]
There were two refs to GitHub for some reason. I have removed the wrong one.
